### ISSUE TITLE
The module zkemkeeper.dll failed to load

### ISSUE THREAD

**Issue by khoait** [ZKTeco/Standalone-SDK#1]
![image](https://user-images.githubusercontent.com/8686497/71305467-5c4ad300-2407-11ea-9a84-767fd61d51e6.png)

I get this error trying to register the dll. Could you advice?

**Comment by checkdigits** [comment]
Are you doing this via an elevated (Administrator) command line?

Also, you're copying via OneDrive - you should copy to a folder other than OneDrive as caching of OneDrive might be interfering.

Can I just check - you're copying the files directly to your System32 directory?  You shouldn't do that as you're not checking any version numbers that way and could overwrite existing versions of the shared DLLs or mix versions of dependencies.  

The best way to do it is to create a folder for your app, copy all of these files into that folder and then run regsvr32 to register the zkmemkeeper DLL in *that* folder.  You can do that from the start-->run prompt like so:

![image](https://user-images.githubusercontent.com/2126394/71310011-6b645d80-23d4-11ea-91a9-45573b051112.png)

**Comment by khoait** [comment]
Thanks @checkdigits 

Creating an app folder outsite of onedrive and register the dll there, works for me! 

By the way, it's your script auto-install_sdk.bat that doing the copy to system32 dir. Or is it just a template script? If so you should mention that in readme :)

Cheers!

**Comment by kcbaruri** [comment]
I have followed the steps below:
1. Copied the .dll file in windows/system32 and executed the command regsvr32 zkemkeeper.dll and received the error above failed to load.
2. Copied the project in a specific file and inside that placed the .dll and received the same error.

Is there any other approach?
